### ISSUE TITLE
DNS resolver

### ISSUE THREAD

**Issue by sdavides** [pepaslabs/pogoplug_static_binaries#2]
Is the system DNS server for the resolver not included?

![immagine](https://github.com/pepaslabs/pogoplug_static_binaries/assets/31100253/eebd6a38-cc95-4829-8191-8eba064a2fd8)

**Comment by cellularmitosis** [comment]
Hmm, can you check if /etc/resolv.conf looks correct?

**Comment by sdavides** [comment]
/etc/resolv.conf is correct.

on the image ping work.

**Comment by sdavides** [comment]
I tried with wget on busybox, it works here
